name: Continuous Deployment Pipeline

permissions:
 id-token: write
 contents: read

on:
  push:
    branches:
      - main
      - develop

jobs:
 terraform:
   name: Terraform Apply
   runs-on: ubuntu-latest
   environment: ${{ github.ref_name == 'main' && 'production' || 'staging' }}
   env:
    WORK_DIR: ./accounts/${{ github.ref_name == 'main' && 'production' || 'staging' }}
    ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
    ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
    ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
    ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

   defaults:
     run:
       shell: bash

   steps:
     - name: Checkout Repository
       uses: actions/checkout@v4

     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v4
       with:
         aws-region: ap-northeast-1
         role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role

     - name: Setup Terraform
       uses: hashicorp/setup-terraform@v3
       with:
         terraform_version: 1.9.8

     - name: Initialize Terraform
       working-directory: ${{ env.WORK_DIR }}
       run: terraform init

     - name: Apply Terraform
       working-directory: ${{ env.WORK_DIR }}
       run: terraform apply -auto-approve

     - name: Notify Slack when job failed
       if: ${{ failure() }}
       uses: slackapi/slack-github-action@v2.1.1
       with:
         payload: |
          {
            "url": "${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}"
          }
         webhook: ${{ secrets.SLACK_WEBHOOK_URL_INFRA }}
         webhook-type: webhook-trigger
